### ISSUE TITLE
NTR: Add 10 TGML colour classes (BODCNVS-1092)

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/H04#3]
The EMODnet chemistry microlitter group has reviewed the existing bibliography and consolidated protocols for microlitter. They are proposing to revise the vocabulary [H04](http://vocab.nerc.ac.uk/collection/H04/current/) with the addition of new colour classes in order to support the MSFD Technical Group on Marine Litter ([TGML](https://mcc.jrc.ec.europa.eu/main/dev.py?N=41&O=434&titre_chap=TG)) protocol.

**Comment by gwemon** [comment]
@mattevi78 @mmolinajack The changes have been implemented and have been queued for publication on the NVS. 10 new colour categories have been added to H04. The definitions to existing records have also been updated as you suggested to reflect the protocols using these classes. The changes will be live on the NVS tomorrow after 0730AM London time.

**Comment by mmolinajack** [comment]
Thanks @gwemon

**Comment by gwemon** [comment]
All updated descriptions and new terms published: http://vocab.nerc.ac.uk/collection/H04/current/
